pipeline:
  name: my-budget
  identifier: mybudget
  projectIdentifier: default
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubhl
        repoName: my-budget
        build: <+input>
  stages:
    - stage:
        name: a
        identifier: a
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: docker ps
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
